/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import clienteCli.Cliente;
import clienteEC.EstadoCivil;
import clienteEC.FindEstadoCivil;
import clienteEC.FindEstadoCivilResponse;
import java.util.List;
import javafx.util.converter.IntegerStringConverter;
import javax.swing.JOptionPane;

/**
 *
 * @author Lennon
 */
public class PanelCrearCliemte extends javax.swing.JPanel {

    /**
     * Creates new form PanelCrearCliemte
     */
    public PanelCrearCliemte() {
        initComponents();
        init();
        
        validacion1.setVisible(false);
        validacion2.setVisible(false);
        validacion3.setVisible(false);
        validacion4.setVisible(false);
        validacion5.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbM = new javax.swing.JRadioButton();
        rbF = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboEstadoCivil = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        validacion1 = new javax.swing.JLabel();
        validacion2 = new javax.swing.JLabel();
        validacion3 = new javax.swing.JLabel();
        validacion4 = new javax.swing.JLabel();
        validacion5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Crear Cliente");

        jLabel2.setText("Rut  :");

        jLabel3.setText("-");

        jLabel4.setText("Nombre  :");

        jLabel5.setText("Apellido  :");

        jLabel6.setText("Sexo  :");

        buttonGroup1.add(rbM);
        rbM.setText("Masculino");

        buttonGroup1.add(rbF);
        rbF.setText("Femenino");

        jLabel7.setText("Edad  :");

        jLabel8.setText("Estado Civil  :");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        validacion1.setForeground(new java.awt.Color(255, 0, 0));
        validacion1.setText("Campo Oblifatorio");

        validacion2.setForeground(new java.awt.Color(255, 0, 0));
        validacion2.setText("Campo Oblifatorio");

        validacion3.setForeground(new java.awt.Color(255, 0, 0));
        validacion3.setText("Campo Oblifatorio");

        validacion4.setForeground(new java.awt.Color(204, 0, 0));
        validacion4.setText("Campo Oblifatorio");

        validacion5.setForeground(new java.awt.Color(204, 0, 0));
        validacion5.setText("Campo Oblifatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellido))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(validacion1)
                                    .addComponent(validacion2)
                                    .addComponent(validacion3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEdad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(validacion4))
                                    .addComponent(validacion5)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validacion1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validacion2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validacion3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbM)
                    .addComponent(rbF)
                    .addComponent(validacion4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validacion5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void init() {

        try {
            cboEstadoCivil.removeAllItems();
            int count = countEstadoCivil();
            if (count > 0) {
                for (int i = 0; i <= count; i++) {
                    EstadoCivil es = findEstadoCivil(i + 1);
                    this.cboEstadoCivil.addItem(es.getDescripcionEstadoCivil());
                }
            }
        } catch (Exception e) {
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            if(valida()){
             
            clienteCli.Cliente c = new clienteCli.Cliente();

            c.setNombreCliente(txtNombre.getText());
            c.setApellidoCliente(txtApellido.getText());
            c.setRut(Integer.parseInt(txtRut.getText()));
            c.setDv(txtDV.getText());
            if (rbM.isSelected()) {
                c.setSexo(true);
            }
            if (rbF.isSelected()) {
                c.setSexo(false);
            }
            int estaC = (cboEstadoCivil.getSelectedIndex() + 1);
            String estaC2 = "" + estaC;

            clienteCli.EstadoCivil e = new clienteCli.EstadoCivil();
            e.setIdEstadoCivil(Short.parseShort(estaC2));
            e.setDescripcionEstadoCivil(cboEstadoCivil.getSelectedItem().toString());
            c.setEstadoCivilIdEstadoCivil(e);
            c.setActivoC(true);
            
            int ed = Integer.parseInt( txtEdad.getText());
            if(ed < 18 ){JOptionPane.showMessageDialog(null, "La edad debe ser mayor o igual a 18");return;}else{
                c.setEdadCliente(Short.parseShort(txtEdad.getText()));
                
            }
            
            if (createCliente(c)) {
                JOptionPane.showMessageDialog(null, "Agrego");
            }
}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO Agrego");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboEstadoCivil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbF;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDV;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JLabel validacion1;
    private javax.swing.JLabel validacion2;
    private javax.swing.JLabel validacion3;
    private javax.swing.JLabel validacion4;
    private javax.swing.JLabel validacion5;
    // End of variables declaration//GEN-END:variables

    private static boolean createCliente(clienteCli.Cliente entity) {
        clienteCli.WSCliente_Service service = new clienteCli.WSCliente_Service();
        clienteCli.WSCliente port = service.getWSClientePort();
        return port.createCliente(entity);
    }

    private static java.util.List<clienteEC.EstadoCivil> findAllEstadoCivil() {
        clienteEC.WSEstadoCivil_Service service = new clienteEC.WSEstadoCivil_Service();
        clienteEC.WSEstadoCivil port = service.getWSEstadoCivilPort();
        return port.findAllEstadoCivil();
    }

    private static EstadoCivil findEstadoCivil(int id) {
        clienteEC.WSEstadoCivil_Service service = new clienteEC.WSEstadoCivil_Service();
        clienteEC.WSEstadoCivil port = service.getWSEstadoCivilPort();
        return port.findEstadoCivil(id);
    }

    private static int countEstadoCivil() {
        clienteEC.WSEstadoCivil_Service service = new clienteEC.WSEstadoCivil_Service();
        clienteEC.WSEstadoCivil port = service.getWSEstadoCivilPort();
        return port.countEstadoCivil();
    }

    private boolean valida() {
        boolean v = true;
        if(txtRut.getText().equals("") && txtDV.getText().equals("")){validacion1.setVisible(true);v=false;}else{validacion1.setVisible(false); }
        if(txtNombre.getText().equals("")){validacion2.setVisible(true);v=false;}else{validacion2.setVisible(false); }
        if(txtApellido.getText().equals("")){validacion3.setVisible(true);v=false;}else{validacion3.setVisible(false); }
        if(rbF.isSelected()|| rbM.isSelected()){validacion4.setVisible(false);}else{validacion4.setVisible(true);v=false; }
        if(txtEdad.getText().equals("")){validacion5.setVisible(true);v=false;}else{validacion5.setVisible(false); }
        
        return v;
    }

}
